# Generated by Django 6.0.4 on 2026-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=120, verbose_name="Jméno zákazníka"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=30, verbose_name="Telefon")),
                ("car_model", models.CharField(max_length=120, verbose_name="Auto")),
                (
                    "tire_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Rozměr pneumatik"
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("change", "Přezutí pneumatik"),
                            ("balance", "Vyvážení kol"),
                            ("storage", "Uskladnění pneumatik"),
                            ("check", "Kontrola tlaku a stavu"),
                        ],
                        max_length=20,
                        verbose_name="Služba",
                    ),
                ),
                ("reservation_date", models.DateField(verbose_name="Datum rezervace")),
                ("reservation_time", models.TimeField(verbose_name="Čas rezervace")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nová"),
                            ("confirmed", "Potvrzená"),
                            ("done", "Dokončená"),
                            ("cancelled", "Zrušená"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Poznámka")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
            ],
            options={
                "ordering": ["reservation_date", "reservation_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation_date", "reservation_time"),
                        name="unique_reservation_slot",
                    )
                ],
            },
        ),
    ]
